# Generated by Django 4.2.7 on 2023-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_license',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
