# Generated by Django 4.2.7 on 2023-11-27 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_driver_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrecord',
            name='fueling_person_name',
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='fueling_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='myapp.fuelingperson'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.vehicle'),
        ),
    ]
