# Generated by Django 4.2.7 on 2023-11-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_fuelrecord_fueling_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='task_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
